import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: [
      "src/lib/__tests__/tariff_import_and_provenance.test.ts",
      "src/lib/__tests__/canonical_tariff_model.test.ts",
      "src/lib/__tests__/production_tariff_engine.test.ts",
      "src/lib/__tests__/demand_reactive_reconciliation.test.ts",
      "src/lib/__tests__/workspace_backup.test.ts",
      "src/lib/__tests__/production_hardening.test.ts",
      "src/lib/__tests__/dashboard_command_centre.test.ts",
      "src/lib/__tests__/secure_ingestion_gateway.test.ts",
      "src/lib/__tests__/adversarial_principal_audit.test.ts",
      "src/lib/__tests__/authoritative_reconciliation_engine.test.ts",
      "src/lib/__tests__/deterministic_calendar_engine.test.ts",
      "src/lib/__tests__/data_governance_subsystem.test.ts",
      "src/lib/__tests__/deterministic_discrepancy_engine.test.ts",
      "src/lib/__tests__/test_public_disclosure_model.test.ts",
      "src/lib/__tests__/test_cta_strategy.test.ts",
      "src/lib/__tests__/test_responsive_viewports.test.ts",
      "src/lib/__tests__/test_performance_audit.test.ts",
      "src/lib/__tests__/test_accessibility_audit.test.ts",
      "src/lib/__tests__/test_seo_structure.test.ts",
      "src/lib/__tests__/test_page_structure_sequence.test.ts",
      "src/lib/__tests__/test_public_website_front_door_audit.test.ts",
      "src/lib/__tests__/test_visual_signature_advanced.test.ts",
      "src/lib/__tests__/test_sp_global_principles_audit.test.ts",
      "src/lib/__tests__/production_data_lifecycle.test.ts",
      "src/lib/__tests__/database_source_of_truth.test.ts",
      "src/lib/__tests__/tenant_isolation.test.ts",
      "src/lib/__tests__/upload_ingestion_pipeline.test.ts",
      "src/lib/__tests__/file_security_adversarial.test.ts",
      "src/lib/__tests__/persistent_storage_lineage.test.ts",
      "src/lib/__tests__/pdf_invoice_ingestion.test.ts",
      "src/lib/__tests__/amr_interval_ingestion.test.ts",
      "src/lib/__tests__/stage10_data_normalisation.test.ts",
      "src/lib/__tests__/stage11_data_quality_engine.test.ts",
      "src/lib/__tests__/stage12_reconciliation_engine.test.ts",
      "src/lib/__tests__/stage13_tariff_engine.test.ts",
      "src/lib/__tests__/stage14_financial_integrity.test.ts",
      "src/lib/__tests__/stage15_automatic_processing.test.ts",
      "src/lib/__tests__/stage16_processing_jobs.test.ts",
      "src/lib/__tests__/stage17_large_datasets.test.ts",
      "src/lib/__tests__/stage18_real_dashboard.test.ts",
      "src/lib/__tests__/stage19_real_charts.test.ts",
      "src/lib/__tests__/stage20_automatic_refresh.test.ts",
      "src/lib/__tests__/stage21_duplicate_protection.test.ts",
      "src/lib/__tests__/stage22_audit_trail.test.ts",
      "src/lib/__tests__/stage23_error_handling.test.ts",
      "src/lib/__tests__/stage24_empty_states.test.ts",
      "src/lib/__tests__/stage25_frontend_backend_contract.test.ts",
      "src/lib/__tests__/stage26_security.test.ts",
      "src/lib/__tests__/stage27_remove_prototype_language.test.ts",
      "src/lib/__tests__/stage28_real_data_verification.test.ts",
      "src/lib/__tests__/stage29_end_to_end.test.ts",
      "src/lib/__tests__/stage30_data_persistence.test.ts",
      "src/lib/__tests__/stage32_observability.test.ts",
      "src/lib/__tests__/stage33_dead_code_elimination.test.ts",
      "src/lib/__tests__/stage34_database_review.test.ts",
      "src/lib/__tests__/stage35_dashboard_review.test.ts",
      "src/lib/__tests__/stage36_security_disclosure.test.ts",
      "src/lib/__tests__/stage37_production_readiness.test.ts",
      "src/lib/__tests__/stage38_final_rule_production_ready.test.ts",
      "src/lib/__tests__/internal_data_lineage_map.test.ts",
      "src/lib/__tests__/stage39_source_of_truth_architecture.test.ts",
      "src/lib/__tests__/document_intelligence_foundation.test.ts",
      "src/lib/__tests__/stage2_document_registry.test.ts",
      "src/lib/__tests__/stage3_pdf_inspection.test.ts",
      "src/lib/__tests__/stage4_page_registry.test.ts",
      "src/lib/__tests__/stage5_text_extraction.test.ts",
      "src/lib/__tests__/stage6_layout_extraction.test.ts",
      "src/lib/__tests__/stage7_document_classification.test.ts",
      "src/lib/__tests__/stage8_document_evidence_model.test.ts",
      "src/lib/__tests__/stage9_extraction_runs.test.ts",
      "src/lib/__tests__/stage10_idempotency_and_duplicates.test.ts",
      "src/lib/__tests__/stage11_error_handling.test.ts",
      "src/lib/__tests__/stage12_security.test.ts",
      "src/lib/__tests__/stage13_frontend_document_view.test.ts",
      "src/lib/__tests__/stage14_document_viewer_foundation.test.ts",
      "src/lib/__tests__/stage15_prepare_ocr_handoff.test.ts",
      "src/lib/__tests__/stage16_database_integration.test.ts",
      "src/lib/__tests__/stage18_real_documents.test.ts",
      "src/lib/__tests__/reconciliation_inputs_and_coverage.test.ts",
      "src/lib/__tests__/reconciliation_data_coverage_and_amr_validation.test.ts",
      "src/lib/__tests__/reconciliation_amr_model_and_timezone.test.ts",
      "src/lib/__tests__/meter_reading_calculation_and_unit_normalisation.test.ts",
      "src/lib/__tests__/reconciliation_power_factor_and_tou_mapping.test.ts",
      "src/lib/__tests__/energy_and_demand_reconciliation.test.ts",
      "src/lib/__tests__/reactive_energy_and_charge_reconciliation.test.ts",
      "src/lib/__tests__/expected_vs_billed_and_variance_engine.test.ts",
    ],
    testTimeout: 60000,
    fileParallelism: false,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
